[package]
authors = ["bRad <brad@humanenginuity.com>"]
name = "hello_led"
version = "0.1.0"

[dependencies]
memmap = "0.5.2"
owning_ref = "0.3.3"

[profile]

[profile.release]
lto = true
opt-level = 3
